version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todoapp_db
      - POSTGRES_USER=todoapp_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=4432
  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py autofill_groups"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    container_name: todo-app
    restart: unless-stopped    
    depends_on:
        - db