version: '3.8'

services:
  web:
    build: ./
    volumes:
      - ./app/:/usr/src/todoapp/
    ports:
      - 8070:8070
    env_file:
      - ./.env
    container_name: todo-app
    restart: unless-stopped