# Generated by Django 4.0.6 on 2022-07-19 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Когда удалена запись')),
                ('subject', models.CharField(max_length=255, verbose_name='Краткое описание задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='полное описание задачи')),
                ('status', models.CharField(choices=[('LATER', 'Отложена'), ('DOING', 'В работе'), ('DONE', 'Исполнена')], default='LATER', max_length=100, verbose_name='Статус задачи')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил запись')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Список задач',
            },
        ),
        migrations.CreateModel(
            name='CardExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Когда удалена запись')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardlist.card', verbose_name='Связь с карточкой')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_executors', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил запись')),
            ],
            options={
                'verbose_name': 'Исполнитель задачи',
                'verbose_name_plural': 'Исполнители задач',
            },
        ),
    ]
