# Generated by Django 4.0.6 on 2022-07-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardexecutor',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executors', to='cardlist.card', verbose_name='Связь с карточкой'),
        ),
        migrations.AlterField(
            model_name='cardexecutor',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
