# Generated by Django 4.0.6 on 2022-07-19 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardlist', '0002_alter_cardexecutor_card_alter_cardexecutor_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил запись'),
        ),
        migrations.AddField(
            model_name='cardexecutor',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил запись'),
        ),
    ]
