# Generated by Django 4.0.6 on 2022-07-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardlist', '0004_alter_cardexecutor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Список задач'},
        ),
    ]
