# Generated by Django 4.0.6 on 2022-07-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardlist', '0006_cardnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnotification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено ли исполнителем'),
        ),
    ]
