# Generated by Django 4.0.6 on 2022-09-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardlist', '0007_cardnotification_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnotification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено ли исполнителю'),
        ),
    ]
